// app/api/support/tickets/route.ts
import { NextRequest, NextResponse } from 'next/server';
import { createSupabaseAdminClient } from '@/lib/supabase-server';
import { requireAuth, requireAdmin } from '@/lib/auth-guard';

// ── GET — list tickets ────────────────────────────────────────
export async function GET(req: NextRequest) {
  const supabase   = createSupabaseAdminClient();
  const params     = req.nextUrl.searchParams;
  const agentId    = params.get('agentId');
  const status     = params.get('status');
  const search     = params.get('search') || '';
  const isAdminReq = params.get('admin') === '1';

  if (isAdminReq) {
    const auth = await requireAdmin(req);
    if (!auth.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  } else {
    const auth = await requireAuth(req);
    if (!auth.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    let query = supabase
      .from('support_tickets')
      .select(`
        *,
        agents!support_tickets_agent_id_fkey(name, slug)
      `)
      .order('last_message_at', { ascending: false });

    if (agentId) query = query.eq('agent_id', agentId);
    if (status && status !== 'all') query = query.eq('status', status);
    if (search) {
      query = query.or(
        `ticket_number.ilike.%${search}%,subject.ilike.%${search}%,transaction_reference.ilike.%${search}%`
      );
    }

    const { data: tickets, error } = await query;
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    // Attach unread counts per ticket
    const ticketIds = (tickets || []).map((t: { id: string }) => t.id);
    let unreadMap: Record<string, number> = {};

    if (ticketIds.length > 0) {
      // For agents: unread = admin messages not yet read
      // For admin:  unread = agent messages not yet read
      const senderFilter = isAdminReq ? 'agent' : 'admin';
      const { data: unreadRows } = await supabase
        .from('ticket_messages')
        .select('ticket_id')
        .in('ticket_id', ticketIds)
        .eq('sender_type', senderFilter)
        .eq('is_read', false);

      (unreadRows || []).forEach((r: { ticket_id: string }) => {
        unreadMap[r.ticket_id] = (unreadMap[r.ticket_id] || 0) + 1;
      });
    }

    const result = (tickets || []).map((t: {
      id: string; agents?: { name: string; slug: string };
    } & Record<string, unknown>) => ({
      ...t,
      agent_name: (t.agents as { name: string; slug: string } | null)?.name || '',
      agent_slug: (t.agents as { name: string; slug: string } | null)?.slug || '',
      unread_count: unreadMap[t.id] || 0,
      agents: undefined,
    }));

    return NextResponse.json(result);
  } catch (e) {
    console.error('[support tickets GET]', e);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}

// ── POST — create ticket ──────────────────────────────────────
export async function POST(req: NextRequest) {
  const auth = await requireAuth(req);
  if (!auth.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const { agentId, subject, category, message, transactionReference } = await req.json();

    if (!agentId || !subject || !category || !message) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const supabase = createSupabaseAdminClient();

    // Verify agent exists
    const { data: agent } = await supabase
      .from('agents').select('id, name').eq('id', agentId).single();
    if (!agent) return NextResponse.json({ error: 'Agent not found' }, { status: 404 });

    // Create ticket (ticket_number auto-generated by trigger)
    const { data: ticket, error: ticketErr } = await supabase
      .from('support_tickets')
      .insert({
        agent_id:              agentId,
        subject,
        category,
        status:                'open',
        priority:              'normal',
        transaction_reference: transactionReference || null,
      })
      .select()
      .single();

    if (ticketErr) return NextResponse.json({ error: ticketErr.message }, { status: 500 });

    // Add first message
    const { error: msgErr } = await supabase
      .from('ticket_messages')
      .insert({
        ticket_id:   ticket.id,
        sender_type: 'agent',
        sender_id:   agentId,
        message,
        is_read:     false,
      });

    if (msgErr) console.error('[support] message insert error:', msgErr);

    // Notify admin of new ticket
    await supabase.from('support_notifications').insert({
      target_type: 'admin',
      agent_id:    agentId,
      ticket_id:   ticket.id,
      title:       '🎫 New Support Ticket',
      message:     `${agent.name} opened ticket ${ticket.ticket_number}: ${subject}`,
      is_read:     false,
    });

    return NextResponse.json({ success: true, ticket });
  } catch (e) {
    console.error('[support tickets POST]', e);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}

// ── PATCH — update ticket status ──────────────────────────────
export async function PATCH(req: NextRequest) {
  const auth = await requireAdmin(req);
  if (!auth.ok) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  try {
    const { ticketId, status, priority } = await req.json();
    if (!ticketId) return NextResponse.json({ error: 'Missing ticketId' }, { status: 400 });

    const supabase = createSupabaseAdminClient();
    const update: Record<string, string> = { updated_at: new Date().toISOString() };
    if (status)   update.status   = status;
    if (priority) update.priority = priority;

    const { data: ticket, error } = await supabase
      .from('support_tickets')
      .update(update)
      .eq('id', ticketId)
      .select('*, agents!support_tickets_agent_id_fkey(id, name)')
      .single();

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    // Notify agent of status change
    if (status) {
      const agentData = ticket.agents as { id: string; name: string } | null;
      if (agentData) {
        const labels: Record<string, string> = {
          resolved: '✅ Your ticket has been resolved',
          closed:   '🔒 Your ticket has been closed',
          pending:  '⏳ Your ticket is under review',
          open:     '🔄 Your ticket has been reopened',
        };
        await supabase.from('support_notifications').insert({
          target_type: 'agent',
          agent_id:    agentData.id,
          ticket_id:   ticketId,
          title:       labels[status] || 'Ticket Updated',
          message:     `Ticket ${ticket.ticket_number} status changed to ${status}.`,
          is_read:     false,
        });
      }
    }

    return NextResponse.json({ success: true });
  } catch (e) {
    console.error('[support tickets PATCH]', e);
    return NextResponse.json({ error: 'Server error' }, { status: 500 });
  }
}
